// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: blockdata/blockfile.proto

package pin

import (
	"reflect"
	"sync"
	"unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockBytesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         [][]byte               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBytesList) Reset() {
	*x = BlockBytesList{}
	mi := &file_blockdata_blockfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBytesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBytesList) ProtoMessage() {}

func (x *BlockBytesList) ProtoReflect() protoreflect.Message {
	mi := &file_blockdata_blockfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBytesList.ProtoReflect.Descriptor instead.
func (*BlockBytesList) Descriptor() ([]byte, []int) {
	return file_blockdata_blockfile_proto_rawDescGZIP(), []int{0}
}

func (x *BlockBytesList) GetItems() [][]byte {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_blockdata_blockfile_proto protoreflect.FileDescriptor

const file_blockdata_blockfile_proto_rawDesc = "" +
	"\n" +
	"\x19blockdata/blockfile.proto\x12\n" +
	"manindexer\"&\n" +
	"\x0eBlockBytesList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\fR\x05itemsBBZ@/srv/dev_project/metaid/metaso-man-indexer/manindexer;manindexerb\x06proto3"

var (
	file_blockdata_blockfile_proto_rawDescOnce sync.Once
	file_blockdata_blockfile_proto_rawDescData []byte
)

func file_blockdata_blockfile_proto_rawDescGZIP() []byte {
	file_blockdata_blockfile_proto_rawDescOnce.Do(func() {
		file_blockdata_blockfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blockdata_blockfile_proto_rawDesc), len(file_blockdata_blockfile_proto_rawDesc)))
	})
	return file_blockdata_blockfile_proto_rawDescData
}

var file_blockdata_blockfile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockdata_blockfile_proto_goTypes = []any{
	(*BlockBytesList)(nil), // 0: manindexer.BlockBytesList
}
var file_blockdata_blockfile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockdata_blockfile_proto_init() }
func file_blockdata_blockfile_proto_init() {
	if File_blockdata_blockfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blockdata_blockfile_proto_rawDesc), len(file_blockdata_blockfile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockdata_blockfile_proto_goTypes,
		DependencyIndexes: file_blockdata_blockfile_proto_depIdxs,
		MessageInfos:      file_blockdata_blockfile_proto_msgTypes,
	}.Build()
	File_blockdata_blockfile_proto = out.File
	file_blockdata_blockfile_proto_goTypes = nil
	file_blockdata_blockfile_proto_depIdxs = nil
}
